# Generated by Django 3.2.25 on 2024-10-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
    ]
